### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by pmoulon** [rust-photogrammetry/p3p#1]
Thank for your launching the rust-photogrammetry initiative. Appreciated you cited all the previous work done around the p3p solver and ports.

I wonder what is your motivation behind porting it to rust.

- Do you have any particular example of performance (time vs. accuracy for C++ vs rust)?
- Do you plan to add some unit test, to ensure people could trust the implementation before incorporating it in their platform?

**Comment by mpizenberg** [comment]
@vadixidav is the main driver behind the rust-photogrammetry initiative, I'm merely helping out ;). By the way if you are interested in participating (or just lurking), here is an invite link to the associated discord server: https://discord.gg/CNHxWjV.

> Do you plan to add some unit test, to ensure people could trust the implementation before incorporating it in their platform?

Regarding tests, I've setup property testing to the package: https://github.com/rust-photogrammetry/p3p/blob/be28b3fa68e59bf6e3f426b8acb38cf506faa674/src/nordberg.rs#L542-L545. So each time you invoke `cargo test` random rotations, translations and image coordinates are generated to test the implementation. According to `cargo test`, it often finds cases where the algorithm does not find the correct camera pose. The test setup is not perfect but sufficient to detect if I'm making a mistake when changing things in the implementation (I modified many things from the C++ implementation).

> Do you have any particular example of performance (time vs. accuracy for C++ vs rust)?

I don't. I haven't spent enough time for this and my use case doesn't require the best performance anyway.

> I wonder what is your motivation behind porting it to rust.

That could be a very long and passionate answer ^^, probably along the lines of what I wrote here: https://github.com/mpizenberg/visual-odometry-rs#background-story. But the shortest, most honest answer is that I really like the Rust language so when I can, I port pieces of code I need to Rust.

And concretely, I'm currently finishing some proof of concept WebAssembly + WebGL application for visual odometry on the web, with additional human interactions (cf image below). The human interaction consists in picking 3 corresponding points on two thumbnail images to re-initialize tracking. So P3P is required only punctually.

![interactive-pose-fixing](https://user-images.githubusercontent.com/2905865/64826218-42a41f00-d5c0-11e9-8105-6f4a09b402c7.png)

Having everything in Rust is much more enjoyable for this wasm use case. If interested, you can test the web app at https://mpizenberg.github.io/interactive-vors/. It requires an RGB-D dataset such that this one already prepared (800 Mb tar to load in the web page): https://www.dropbox.com/s/z6tqxskm5fw2pxz/data-full-800mo.tar?dl=0

**Comment by vadixidav** [comment]
@mpizenberg I wouldn't credit me too much! I think we have both written about the same amount so far, and I have focused mostly on feature extraction and matching, whereas you have really focused on odometry pose estimation and resectioning.

@pmoulon I definitely encourage you to join the Rust Photogrammetry Discord server if you are interested in chatting about Rust Photogrammetry. My personal motivation is that I do Photogrammetry mostly with OpenCV in C++ and Python, and I definitely dislike maintaining C++ code (for SLAM) because of the amount of bugs, difficulty of modifying existing codebases, and difficulty of parallelizing the code safely. In addition to that, I really enjoy coding in Rust, and I would like to be able to use it at work and in my spare time to work on these cool projects. If you have any ideas or tips for us, or you are interested in us making something you might use, drop us a message in the Discord server. Anyone is welcome.

**Comment by vadixidav** [comment]
I am going to close this since it isn't an actionable item. For anyone interested in the project (now called rust-cv), please join the Discord server at https://discord.gg/d32jaam.
